# Generated by Django 2.1.3 on 2018-11-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='parent',
        ),
    ]
